name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: ls -la build # Adjust the directory if your build output is different

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: build # Adjust this to your actual build output directory

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: build # Adjust this to your actual build output directory

      - name: Deploy to Server
        run: |
          # Example deployment script
          # Replace with your actual deployment method
          rsync -avz build/ user@yourserver.com:/path/to/deploy

      - name: Start Application
        run: |
          ssh user@yourserver.com 'pm2 restart your-app-name' # Example command to restart your app on the server
